[env:lolin_s2_pico]
platform = espressif32
board = lolin_s2_pico
framework = arduino
monitor_speed = 115200

; Uncomment and set to your port if multiple devices are connected.
upload_port = COM16

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  ESP32Ping
  CNMAT/OSC

extra_scripts =
  post:scripts/post_build_cache.py

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=0
  -I include
